server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath*:com/github/fashionbrot/mapper/xml/*.xml
  type-aliases-package: com.github.fashionbrot.entity


mybatis:
  generate:
    cache:
      path:
      file-name: mybatis-generate-cache